name: Flutter Local Build

on:
  push:
    branches:
      - main

jobs:
  build:
    name: Build on Local Mac
    runs-on: self-hosted

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Install Dependencies
        run: flutter pub get

      - name: Analyze Code
        run: flutter analyze

      - name: Build Android APK
        run: flutter build apk --debug

      - name: Build iOS (No Codesign)
        run: flutter build ios --debug --no-codesign
